
project_id = "ynfyvoljmkxtiezfxcku"

[functions.handle-stripe-webhook]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.check-subscription-status]
verify_jwt = false

[functions.create-customer-portal]
verify_jwt = false

[functions.cleanup-storage]
verify_jwt = false

[functions.interview-questions]
verify_jwt = false

[functions.interview-assistant]
verify_jwt = false

[functions.career-roadmap-analysis]
verify_jwt = false
