
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynfyvoljmkxtiezfxcku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluZnl2b2xqbWt4dGllemZ4Y2t1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NzY5MjIsImV4cCI6MjA2MjA1MjkyMn0.XtbtuCQkZR2DtZZl282FQXbNdU7gA1HpX4pvTGQpTXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
